### ISSUE TITLE
Where/what is data/sql-words?

### ISSUE THREAD

**Issue by terbo** [capnrefsmmat/seuss#3]
I haven't found any references to this file to get this program working, it seems pretty neat, can you give me any tips?

**Comment by Pragueham** [comment]
Create a folder called data in your seuss directory.

**Comment by capnrefsmmat** [comment]
sql-words is an sqlite database containing the rhyming dictionary. I will try to push all the requisite files this weekend, perhaps. Sorry about that.

**Comment by Pragueham** [comment]
That would be great, it looks like fun.

**Comment by capnrefsmmat** [comment]
I just updated the repository to contain the data file, and updated the README with more detailed instructions on how to get up and running. Hope you get it going; it's great fun.

**Comment by Pragueham** [comment]
Just tested - works perfectly.  Thanks for this great resource.

D

**Comment by Pragueham** [comment]
Just tested - works perfectly.  Thanks for this great resource.

D

**Comment by capnrefsmmat** [comment]
I'd love to hear about any interesting source material people use with seuss. My most recent addition was press releases from North Korea so I can produce poems about the imperialist aggressor forces of the US.
