### ISSUE TITLE
Heads up: this project will not run

### ISSUE THREAD

**Issue by teirce** [capnrefsmmat/seuss#4]
Hi all,

I know this is an old project that is abandoned, however I would just like to warn others that were hoping to play with this like I was that the project will not actually run. Currently it produces an index out of bounds error at the beginning of generating the poem. I followed all set up instructions and am running Python 2.7.

If the author happens to know what is going on (unlikely after some odd years) then that would be nice to fix, otherwise just let it be known

**Comment by mooeypoo** [comment]
Actually, @teirce can you post the full error that you're getting? It will help capnrefsmmat (or anyone else who may be interested) fix this issue, and it might actually be something relatively simple to fix.

**Comment by teirce** [comment]
@mooeypoo  
Actually, after digging with this a little bit, I have discovered the problem and it is actually my own fault. Allow me to document in case someone else makes the same mistake.

I, for some unknown reason, thought that the project came with some sample sources cached somewhere -- it was honestly silly of me because I set the project up, I know there weren't any extraneous files.

Anyway, I was attempting to generate a poem from a source that didn't exist. I saw "bible" in the people dictionary and attempted to use it. Again, how silly. The source isn't there so the following error was produced:

```
C:\Python27\python.exe C:/Users/JD/PycharmProjects/seuss/rhyme.py
Traceback (most recent call last):
  File "C:/Users/JD/PycharmProjects/seuss/rhyme.py", line 228, in <module>
    poem = gen.next()
  File "C:/Users/JD/PycharmProjects/seuss/rhyme.py", line 171, in next
    self.getPoem()
  File "C:/Users/JD/PycharmProjects/seuss/rhyme.py", line 165, in getPoem
    self.poem.append(" ".join(self.getLine(person, i)))
  File "C:/Users/JD/PycharmProjects/seuss/rhyme.py", line 135, in getLine
    newWord = self.getRhymingWord(curLine, person)
  File "C:/Users/JD/PycharmProjects/seuss/rhyme.py", line 87, in getRhymingWord
    rhymeWord = self.poem[rhymeLine].split()[-1]
IndexError: list index out of range
```

Once you use a source that actually exists, the program works fine ^^

I'm genuinely sorry for needlessly bothering everyone who has followed this repo, and the creator. This can be closed

**Comment by mooeypoo** [comment]
Awesome, glad it works now, @teirce. No need to be sorry, I just wanted to make sure the system works for those who want to use it!

**Comment by capnrefsmmat** [comment]
Thanks, @mooeypoo. Yeah, I didn't include any sources because of potential copyright issues with including big texts. I'd suggest [Project Gutenberg](http://www.gutenberg.org/) as a good place to find public domain source materials.
